module DF = Dockerfile

let ( @@ ) = Dockerfile.( @@ )

let tarball_filename (s : Spec.t) (t : Target.t) =
  Fmt.str "%s-%s-linux-%s-static.tar.gz" s.package s.version t.arch

let dockerfile (s : Spec.t) (t : Target.t) =
  let apk_build_pkgs =
    "build-base m4 perl pkgconf git curl bash patch gmp-dev sqlite-dev \
     sqlite-static openssl-dev openssl-libs-static zlib-dev zlib-static"
  in
  DF.comment "Generated by `oi dist pkg` — static musl build of %s on alpine."
    s.package
  @@ DF.parser_directive (`Syntax "docker/dockerfile:1.6")
  @@ DF.from ~alias:"oi-builder" t.base_image
  @@ DF.user "root"
  @@ DF.run "apk add --no-cache %s" apk_build_pkgs
  @@ DF.user "opam"
  @@ DF.workdir "/home/opam/src"
  @@ DF.copy ~chown:"opam:opam"
       ~src:[ Fmt.str "%s-%s.tar.gz" s.package s.version ]
       ~dst:"/home/opam/src/" ()
  @@ DF.env [ ("OI_STATIC", "1"); ("CI", "true") ]
  @@ DF.run
       "tar -xzf %s-%s.tar.gz && cd %s-%s && ./build.sh build $(nproc) && \
        ./build.sh install /usr /dist"
       s.package s.version s.package s.version
  @@ DF.comment "=== final: just the static binaries ==="
  @@ DF.from "scratch"
  @@ DF.copy ~from:"oi-builder" ~src:[ "/dist/usr/bin" ] ~dst:"/bin" ()

let build_sh (s : Spec.t) (t : Target.t) =
  let tarball = tarball_filename s t in
  Fmt.str
    {|#!/bin/sh
# Generated by `oi dist pkg`. Builds the static-musl Dockerfile, extracts
# the binaries, and emits %s plus its sha256 sidecar.
set -eu
HERE="$(cd "$(dirname "$0")" && pwd)"
STAGE="$HERE/.staging"
rm -rf "$STAGE"; mkdir -p "$STAGE"
docker buildx build \
  --file "$HERE/Dockerfile" \
  --output type=local,dest="$STAGE" \
  --build-context bundle="$HERE/.." \
  "$HERE/.." 2>/dev/null || \
docker buildx build \
  --file "$HERE/Dockerfile" \
  --output type=local,dest="$STAGE" \
  "$HERE/.."
# The Dockerfile's final stage is scratch with /bin -> the static binaries.
tar --transform 's,^./,%s-%s-linux-%s-static/,' \
    -czf "$HERE/%s" -C "$STAGE/bin" .
( cd "$HERE" && sha256sum "%s" > "%s.sha256" )
rm -rf "$STAGE"
echo "wrote $HERE/%s"
|}
    tarball s.package s.version t.arch tarball tarball tarball tarball
