module DF = Dockerfile

let ( @@ ) = Dockerfile.( @@ )

let epoch_tag (s : Spec.t) =
  match s.epoch with
  | Some n when n > 0 -> Fmt.str "Epoch:          %d\n" n
  | _ -> ""

let epoch_evr (s : Spec.t) =
  match s.epoch with Some n when n > 0 -> Fmt.str "%d:" n | _ -> ""

(* Base toolchain for an rpm-family build. *)
let base_build_depexts =
  [
    "gcc"; "gcc-c++"; "make"; "m4"; "perl-interpreter"; "pkgconf-pkg-config";
    "patch"; "rsync"; "tar"; "gzip"; "bzip2"; "xz"; "zstd";
    "git"; "curl"; "ca-certificates"; "ocaml";
  ]

(* Tools to drive rpmbuild itself. *)
let tooling = [ "rpm-build"; "rpmdevtools" ]

let combined_install ~overlay_depexts =
  base_build_depexts @ tooling @ overlay_depexts
  |> List.sort_uniq String.compare
  |> String.concat " "

let dist_macro (t : Target.t) =
  (* The [%{?dist}] suffix on [Release:] picks up the build chroot's
     distribution tag automatically (e.g. [.fc44]). [t.tag] is only used
     in the filename helper below for explicitness. *)
  match t.distro with
  | Some (`Fedora _) -> "%{?dist}"
  | Some (`CentOS _ | `OracleLinux _) -> "%{?dist}"
  | _ -> ""

let rpmrel (t : Target.t) = Option.value ~default:"1" t.rpmrel

let spec (s : Spec.t) (t : Target.t) ~overlay_depexts ~date_rpm =
  let prefix_each pfx xs =
    xs |> List.map (fun x -> pfx ^ x) |> String.concat "\n"
  in
  let build_requires =
    base_build_depexts @ overlay_depexts
    |> List.sort_uniq String.compare
    |> prefix_each "BuildRequires:  "
  in
  let requires =
    overlay_depexts
    |> List.filter (fun d -> not (String.length d > 0 && d.[0] = '-'))
    |> List.sort_uniq String.compare
    |> prefix_each "Requires:       "
  in
  Fmt.str
    "Name:           %s\n\
     %sVersion:        %s\n\
     Release:        %s%s\n\
     Summary:        %s\n\
     License:        %s\n\
     URL:            %s\n\
     Source0:        %s-%s.tar.gz\n\
     ExclusiveArch:  %s aarch64\n\n\
     %s\n%s\n\n\
     %%description\n\
     %s\n\n\
     %%prep\n\
     %%autosetup -n %s-%s\n\n\
     %%build\n\
     ./build.sh build %%{?_smp_build_ncpus}%%{!?_smp_build_ncpus:$(nproc)}\n\n\
     %%install\n\
     ./build.sh install %s %%{buildroot}\n\n\
     %%files\n\
     %s/bin/*\n\
     %s/share/*\n\n\
     %%changelog\n\
     * %s %s - %s%s-%s\n\
     - Packaged by osdist from the oi dist bundle.\n"
    s.package (epoch_tag s) s.version (rpmrel t) (dist_macro t)
    (if s.synopsis = "" then "Packaged by osdist" else s.synopsis)
    s.license
    (if s.homepage = "" then "https://example.org" else s.homepage)
    s.package s.version
    (match t.arch with "x86_64" -> "x86_64" | a -> a)
    build_requires requires
    (if s.description = "" then s.synopsis else s.description)
    s.package s.version s.prefix s.prefix s.prefix date_rpm s.maintainer
    (epoch_evr s) s.version (rpmrel t)

let filename (s : Spec.t) (t : Target.t) =
  let dist =
    match t.distro with
    | Some (`Fedora `V44) -> ".fc44"
    | Some (`Fedora `V43) -> ".fc43"
    | Some (`Fedora `V42) -> ".fc42"
    | Some (`Fedora _) -> ".fc"
    | _ -> ""
  in
  Fmt.str "%s-%s-%s%s.%s.rpm" s.package s.version (rpmrel t) dist t.arch

let dockerfile (s : Spec.t) (t : Target.t) ~overlay_depexts =
  let pkgs = combined_install ~overlay_depexts in
  DF.comment "Generated by `oi dist pkg` — build %s (.rpm)" t.tag
  @@ DF.parser_directive (`Syntax "docker/dockerfile:1.6")
  @@ DF.from ~alias:"build" t.base_image
  @@ DF.run "dnf -y install %s && dnf clean all" pkgs
  @@ DF.run "useradd -u 1000 -m builder"
  @@ DF.user "builder"
  @@ DF.workdir "/home/builder"
  @@ DF.run "rpmdev-setuptree"
  @@ DF.copy ~chown:"builder:builder"
       ~src:[ Fmt.str "%s-%s.tar.gz" s.package s.version ]
       ~dst:(Fmt.str "/home/builder/rpmbuild/SOURCES/%s-%s.tar.gz"
               s.package s.version)
       ()
  @@ DF.copy ~chown:"builder:builder"
       ~src:[ Fmt.str "%s.spec" s.package ]
       ~dst:(Fmt.str "/home/builder/rpmbuild/SPECS/%s.spec" s.package)
       ()
  @@ DF.run
       "rpmbuild -bb --define \"_topdir /home/builder/rpmbuild\" \
        rpmbuild/SPECS/%s.spec"
       s.package
  @@ DF.comment "=== final: just the .rpm ==="
  @@ DF.from "scratch"
  @@ DF.copy ~from:"build"
       ~src:[ Fmt.str "/home/builder/rpmbuild/RPMS/%s/*.rpm" t.arch ]
       ~dst:"/" ()
