[@@@ai_disclosure "ai-assisted"]
[@@@ai_model "claude-opus-4-6"]
[@@@ai_provider "Anthropic"]

let ( / ) = Filename.concat

(* Canonicalise [p] to an absolute path. Relative paths in OCAMLFIND_CONF /
   OCAMLLIB break dune (Path.External.of_string rejects them). Falls back to
   the original string if the path does not yet exist on disk. *)
let canonical p =
  try Unix.realpath p with Unix.Unix_error _ -> p

(* -- OCaml-specific environment ------------------------------------------ *)

let env_vars ~prefix ~dune_cache_root =
  let prefix = canonical prefix in
  Opam_ctx.switch_env ~prefix
  @ [
      ("OCAMLFIND_DESTDIR", prefix / "lib");
      ("DUNE_CACHE", "enabled");
      ("DUNE_CACHE_ROOT", dune_cache_root);
      ("DUNE_CACHE_STORAGE_MODE", "hardlink");
    ]

let envrc_content ~prefix ~dune_cache_root =
  let prefix = canonical prefix in
  let switch_vars =
    List.map
      (fun (k, v) -> Fmt.str "export %s=\"%s\"" k v)
      (Opam_ctx.switch_env ~prefix)
  in
  String.concat "\n"
    ([
       "# Generated by oi sync — do not edit";
       Fmt.str "OI_PREFIX=$(expand_path %s)" prefix;
       Fmt.str "OI_CACHE=$(expand_path %s)" dune_cache_root;
       "";
       "PATH_add \"$OI_PREFIX/bin\"";
     ]
    @ switch_vars
    @ [
        Fmt.str "export OCAMLFIND_DESTDIR=\"$OI_PREFIX/lib\"";
        "export DUNE_CACHE=enabled";
        Fmt.str "export DUNE_CACHE_ROOT=\"$OI_CACHE\"";
        "export DUNE_CACHE_STORAGE_MODE=hardlink";
        "";
      ])

let make_env ~prefix ~dune_cache_root =
  let vars = env_vars ~prefix ~dune_cache_root in
  let dominated =
    "PATH" :: List.map (fun (k, _) -> String.uppercase_ascii k) vars
  in
  let has_prefix s k =
    let k = k ^ "=" in
    String.length s >= String.length k
    && String.uppercase_ascii (String.sub s 0 (String.length k)) = k
  in
  let current_path =
    try Sys.getenv "PATH" with Not_found -> "/usr/bin:/bin"
  in
  let base =
    Unix.environment () |> Array.to_list
    |> List.filter (fun s -> not (List.exists (has_prefix s) dominated))
  in
  let path_entry = "PATH=" ^ (prefix / "bin") ^ ":" ^ current_path in
  let env_pairs =
    path_entry :: List.map (fun (k, v) -> k ^ "=" ^ v) vars
  in
  Array.of_list (env_pairs @ base)
