[@@@ai_disclosure "ai-assisted"]
[@@@ai_model "claude-opus-4-7"]
[@@@ai_provider "Anthropic"]

(* Pin-depends materialisation. Re-exported as [Source.Pin]. *)

let ( / ) = Filename.concat
let log_src = Logs.Src.create "oi.source.pin"

module Log = (val Logs.src_log log_src : Logs.LOG)

let url_key (url : OpamUrl.t) =
  Digest.to_hex (Digest.string (OpamUrl.to_string url))

let sentinel_path src_dir = src_dir / ".oi-pin-ok"

(* -- oi.lock: per-project pin-depends resolution snapshot ------------ *)

module Lock = struct
  (* [oi.lock] is transient state, kept under [_oi/] so it's
     gitignored alongside the rest of the build artefacts. Pin
     resolution is repeated on demand if the file is missing. *)
  let rel_path = "_oi" / "oi.lock"

  type entry = { pkg : string; origin : string; resolved : string }

  let parse_entries (sexps : Sexplib0.Sexp.t list) =
    let find_kv key fields =
      List.find_map
        (function
          | Sexplib0.Sexp.List [ Atom k; Atom v ] when k = key -> Some v
          | _ -> None)
        fields
    in
    let tbl = Hashtbl.create 16 in
    List.iter
      (function
        | Sexplib0.Sexp.List (Atom "pin" :: Atom pkg :: fields) ->
            begin match
              (find_kv "origin" fields, find_kv "resolved" fields)
            with
            | Some origin, Some resolved ->
                Hashtbl.replace tbl (pkg, origin) { pkg; origin; resolved }
            | _ -> ()
            end
        | _ -> ())
      sexps;
    tbl

  let read ~fs ~project_root =
    let path = project_root / rel_path in
    if not (Sys.file_exists path) then Hashtbl.create 0
    else
      let content = Eio.Path.load Eio.Path.(fs / path) in
      match Parsexp.Many.parse_string content with
      | Ok sexps -> parse_entries sexps
      | Error e ->
          Log.warn (fun m ->
              m "%s: parse error (%s); ignoring lock file" path
                (Parsexp.Parse_error.message e));
          Hashtbl.create 0

  let write ~fs ~project_root entries =
    let path = project_root / rel_path in
    Eio.Path.mkdirs ~exists_ok:true ~perm:0o755
      Eio.Path.(fs / Filename.dirname path);
    let buf = Buffer.create 512 in
    Buffer.add_string buf
      ";; _oi/oi.lock — transient. Auto-regenerated by `oi build`.\n\
       ;; Records the sha each pin-depends URL resolved to so subsequent\n\
       ;; builds skip the ls-remote round-trip; safe to delete to force a\n\
       ;; refresh.\n";
    Buffer.add_string buf "(version 1)\n";
    let sorted = List.sort (fun a b -> String.compare a.pkg b.pkg) entries in
    let pp = Fmt.with_buffer buf in
    List.iter
      (fun e ->
        Fmt.pf pp "(pin %s\n  (origin   %S)\n  (resolved %S))\n" e.pkg e.origin
          e.resolved)
      sorted;
    Eio.Path.save ~create:(`Or_truncate 0o644)
      Eio.Path.(fs / path)
      (Buffer.contents buf)
end

(* Resolve every pin's URL into a sha-pinned (or already content-
   addressed) form, consulting/refreshing oi.lock at [lock_dir]. The
   returned list has the same shape and order as [pins], but with each
   [Project.pin.url] swapped for its resolved URL — downstream
   [fetch_pin] then clones at exactly that sha. *)
let resolve_pin_url ~fs ~sys ~pkg_s ~origin (pin : Project.pin) =
  match
    Source_reporepo.try_resolve_url ~fs ~sys ~where:pkg_s pin.url
      ~has_checksum:false
  with
  | `Keep -> pin.url
  | `Replace_url u -> u
  (* Tarball pin without checksum: format has no checksum slot, so we
     leave the URL alone. *)
  | `Add_checksum _ -> pin.url
  | `Failed reason ->
      Error.fail_config_error "pin %s: cannot resolve URL %s: %s" pkg_s origin
        reason

let resolve_with_lock ~fs ~sys ~tbl ~pkg_s ~origin pin =
  match Hashtbl.find_opt tbl (pkg_s, origin) with
  | Some (entry : Lock.entry) -> OpamUrl.parse entry.resolved
  | None -> resolve_pin_url ~fs ~sys ~pkg_s ~origin pin

let fold_pin_resolution ~fs ~sys ~tbl pins =
  List.fold_right
    (fun (pin : Project.pin) (pins_acc, entries_acc) ->
      let pkg_s = OpamPackage.to_string pin.pkg in
      let origin = OpamUrl.to_string pin.url in
      let resolved_url = resolve_with_lock ~fs ~sys ~tbl ~pkg_s ~origin pin in
      let entry =
        { Lock.pkg = pkg_s; origin; resolved = OpamUrl.to_string resolved_url }
      in
      ({ pin with url = resolved_url } :: pins_acc, entry :: entries_acc))
    pins ([], [])

let resolve_pins ~fs ~sys ?project_root pins =
  match (pins, project_root) with
  | [], _ | _, None -> pins
  | _, Some project_root ->
      let tbl = Lock.read ~fs ~project_root in
      let pins', entries = fold_pin_resolution ~fs ~sys ~tbl pins in
      let entry_key (e : Lock.entry) = (e.pkg, e.origin, e.resolved) in
      let sorted_keys items = List.sort compare (List.map entry_key items) in
      let prev = Hashtbl.fold (fun _ v acc -> v :: acc) tbl [] |> sorted_keys in
      if sorted_keys entries <> prev then begin
        Lock.write ~fs ~project_root entries;
        Log.info (fun m ->
            m "Wrote %s with %d pin(s)"
              (project_root / Lock.rel_path)
              (List.length entries))
      end;
      pins'

let fetch_pin ?(reporter = Build_progress.null) ~fs ~cache ~refresh
    (pin : Project.pin) =
  let root = Cache.pins_dir cache in
  let src_dir = root / "sources" / url_key pin.url in
  let sentinel = sentinel_path src_dir in
  if Cache.fresh ~refresh ~sentinel ~max_age:Cache.refresh_max_age then src_dir
  else begin
    Log.info (fun m ->
        m "Fetching pin %s from %s"
          (OpamPackage.to_string pin.pkg)
          (OpamUrl.to_string pin.url));
    Fmt.kstr
      (fun s -> reporter.Build_progress.event (Status s))
      "Fetching pin %s"
      (OpamPackage.to_string pin.pkg);
    if Sys.file_exists src_dir then
      Eio.Path.rmtree ~missing_ok:true Eio.Path.(fs / src_dir);
    let dst = OpamFilename.Dir.of_string src_dir in
    OpamFilename.mkdir dst;
    let cache_dir =
      OpamRepositoryPath.download_cache OpamStateConfig.(!r.root_dir)
    in
    let result =
      OpamRepository.pull_tree
        (OpamPackage.to_string pin.pkg)
        ~cache_dir dst [] [ pin.url ]
      |> OpamProcess.Job.run
    in
    match result with
    | OpamTypes.Result _ | OpamTypes.Up_to_date _ ->
        Eio.Path.save ~create:(`Or_truncate 0o644) Eio.Path.(fs / sentinel) "";
        src_dir
    | OpamTypes.Not_available (_, msg) ->
        Error.fail_config_error "pin %s: fetch failed (%s): %s"
          (OpamPackage.to_string pin.pkg)
          (OpamUrl.to_string pin.url)
          msg
  end

let resolved_revision ~sys (pin : Project.pin) ~src_dir =
  match pin.url.OpamUrl.backend with
  | `git -> (
      try
        D10.Sysops.Cmd.run_out sys [ "git"; "-C"; src_dir; "rev-parse"; "HEAD" ]
      with Failure _ -> url_key pin.url)
  | _ -> url_key pin.url

let locate_opam_file ~src_dir (pin : Project.pin) =
  let name = OpamPackage.Name.to_string (OpamPackage.name pin.pkg) in
  let candidates = [ src_dir / (name ^ ".opam"); src_dir / "opam" ] in
  match List.find_opt Sys.file_exists candidates with
  | Some p -> p
  | None ->
      Error.fail_config_error
        "pin %s: no %s.opam or opam file at the root of %s"
        (OpamPackage.to_string pin.pkg)
        name src_dir

let rewrite_opam ~src_dir ~opam_path ~revision (pin : Project.pin) =
  let opam =
    try OpamFile.OPAM.read (OpamFile.make (OpamFilename.raw opam_path))
    with exn ->
      Error.fail_config_error "pin: failed to read %s: %s" opam_path
        (Printexc.to_string exn)
  in
  let local_url = Fmt.kstr OpamUrl.of_string "file://%s#%s" src_dir revision in
  let new_url = OpamFile.URL.create local_url in
  opam
  |> OpamFile.OPAM.with_url new_url
  |> OpamFile.OPAM.with_name (OpamPackage.name pin.pkg)
  |> OpamFile.OPAM.with_version (OpamPackage.version pin.pkg)

let write_repo_marker ~fs ~dir =
  let repo_path = dir / "repo" in
  let path = Eio.Path.(fs / repo_path) in
  Eio.Path.save ~create:(`If_missing 0o644) path "opam-version: \"2.0\"\n"

let write_pin_opam ~packages_dir (pin : Project.pin) opam =
  let name = OpamPackage.Name.to_string (OpamPackage.name pin.pkg) in
  let pkg_s = OpamPackage.to_string pin.pkg in
  let dir = packages_dir / name / pkg_s in
  OpamFilename.mkdir (OpamFilename.Dir.of_string dir);
  let target = dir / "opam" in
  OpamFile.OPAM.write (OpamFile.make (OpamFilename.raw target)) opam

type resolved = { pin : Project.pin; opam : OpamFile.OPAM.t; revision : string }

let materialize ?(reporter = Build_progress.null) ~fs ~sys ~cache
    ?(refresh = false) pins =
  match pins with
  | [] -> None
  | _ ->
      let total = List.length pins in
      Fmt.kstr
        (fun s -> reporter.Build_progress.event (Status s))
        "Materialising %d pin(s)" total;
      let counter = ref 0 in
      let resolved =
        List.map
          (fun (pin : Project.pin) ->
            let src_dir = fetch_pin ~reporter ~fs ~cache ~refresh pin in
            let opam_path = locate_opam_file ~src_dir pin in
            let revision = resolved_revision ~sys pin ~src_dir in
            let opam = rewrite_opam ~src_dir ~opam_path ~revision pin in
            incr counter;
            reporter.Build_progress.event
              (Aggregate { phase = Fetching; total; current = !counter });
            { pin; opam; revision })
          pins
      in
      let triples =
        List.map
          (fun r ->
            let name =
              OpamPackage.Name.to_string (OpamPackage.name r.pin.pkg)
            in
            let version = OpamPackage.version_to_string r.pin.pkg in
            (name, version, r.revision))
          resolved
        |> List.sort compare
      in
      let set_hash =
        let s =
          String.concat "\n"
            (List.map (fun (n, v, r) -> Fmt.str "%s\t%s\t%s" n v r) triples)
        in
        Digest.to_hex (Digest.string s)
      in
      let root = Cache.pins_dir cache in
      let set_root = root / "sets" / set_hash in
      let packages_dir = set_root / "packages" in
      Eio.Path.mkdirs ~exists_ok:true ~perm:0o755 Eio.Path.(fs / packages_dir);
      write_repo_marker ~fs ~dir:set_root;
      List.iter (fun r -> write_pin_opam ~packages_dir r.pin r.opam) resolved;
      Log.info (fun m ->
          m "Materialized %d pin(s) at %s" (List.length pins) packages_dir);
      Some packages_dir
