(library
 (name oi_cmd)
 (libraries
  oi
  d10
  d10ir
  d10ir_cmd
  osrel
  osdist
  cmdliner
  dune-build-info
  fmt
  fmt.tty
  fmt.cli
  logs
  logs.cli
  logs.fmt
  eio
  eio_posix
  eio.unix
  nox-xdg
  nox-tty
  nox-tty-eio
  progress
  dockerfile-opam
  jsont
  jsont.bytesrw
  parsexp
  sexplib0
  dockerfile))
