(* Source-bundle production for {!Osdist_pkg}. Drives the existing
   {!Dist_runner} makefile flow into a staging dir, adds a [build.sh]
   wrapper + README, tars the result with a stable mtime/owner, and
   computes per-distro overlay depexts for the sidecar.

   No cmdliner surface — this used to be a standalone [oi dist bundle]
   command but has since been folded into [oi dist pkg] so a single
   invocation produces both the source tarball and the per-distro
   packaging tree. *)

let ( / ) = Filename.concat

(* build.sh inside the bundle. The deb [rules] and rpm [%%build] /
   [%%install] sections both call into this so the same shell command
   shape works on both families.
   - [build N]: drive [make] with -j N
   - [install PREFIX DESTDIR]: invoke [make install] with the staged path *)
let bundle_build_sh =
  {|#!/bin/sh
# Generated by `oi dist pkg`. Entry point for distro packaging: per-family
# rules/spec files call ./build.sh {build|install} ... so the same Makefile
# is driven uniformly from both .deb and .rpm flows.
set -eu
case "${1:-}" in
  build)
    shift
    j="${1:-2}"
    exec make -j"$j"
    ;;
  install)
    shift
    prefix="${1:?prefix required}"
    destdir="${2:?destdir required}"
    exec make install PREFIX="$prefix" DESTDIR="$destdir"
    ;;
  *)
    echo "usage: $0 {build JOBS | install PREFIX DESTDIR}" >&2
    exit 2
    ;;
esac
|}

let bundle_readme (spec : Osdist.Spec.t) =
  Fmt.str
    {|# %s — source bundle

This self-contained tarball builds %s %s from sources without [oi] or
[opam] at build time — only [make], [curl], [tar+zstd] and a host
OCaml toolchain.

  ./build.sh build "$(nproc)"
  ./build.sh install /usr "$DESTDIR"

The accompanying `<%s-%s.osdist.json>` carries the metadata the
per-distro packaging tree consumes (maintainer, license, per-distro
depexts, …). Both files are produced together by `oi dist pkg`.
|}
    spec.package spec.package spec.version spec.package spec.version

let write_file ~path s ~mode =
  let tmp = Fmt.str "%s.tmp.%d" path (Unix.getpid ()) in
  Out_channel.with_open_bin tmp (fun oc -> Out_channel.output_string oc s);
  Unix.chmod tmp mode;
  Sys.rename tmp path

let pp_argv ppf argv =
  Fmt.pf ppf "%s" (String.concat " " (List.map Filename.quote argv))

let cmd_run ~sys argv =
  try D10.Sysops.Cmd.run sys argv
  with Eio.Io _ as exn ->
    Oi.Error.fail_config_error "oi dist pkg (bundle): %a failed: %s" pp_argv
      argv (Printexc.to_string exn)

let cmd_out ~sys argv =
  try D10.Sysops.Cmd.run_out sys argv
  with Eio.Io _ as exn ->
    Oi.Error.fail_config_error "oi dist pkg (bundle): %a failed: %s" pp_argv
      argv (Printexc.to_string exn)

(* Compute per-distro overlay depexts and key them by
   [Distro.tag_of_distro] so [oi dist pkg]'s materialiser can look them
   up by Target.tag. The alpine-static target's depexts ride the same
   probe — its [distro] is pinned to [`Alpine `V3_22] so e.g.
   [linux-headers] from [uring]'s alpine depexts: stanza lands on the
   apk install line. *)
let compute_depexts ~harness ~refresh : (string * string list) list =
  let { Harness.fs; sys; cache; data_dir; platform; _ } = harness in
  let distros =
    List.map
      (fun (t : Osdist.Target.t) -> t.distro)
      Osdist.Target.default_targets
  in
  let raw =
    try
      Build.compute_overlay_depexts_per_distro ~fs ~sys ~cache ~data_dir
        ~refresh ~platform ~distros
    with exn ->
      Oi.Say.warn "depext probe failed: %s; bundle ships empty depexts"
        (Printexc.to_string exn);
      List.map (fun d -> (d, [])) distros
  in
  List.map
    (fun (d, l) ->
      ( Dockerfile_opam.Distro.tag_of_distro d,
        List.sort_uniq String.compare l ))
    raw

(* Coerce a resolved opam version into a packaging-friendly form. Both
   Debian and RPM require the upstream version to start with a digit;
   the opam convention for unreleased / VCS-tracking packages is a bare
   ["dev"] string, which trips dpkg-buildpackage with
   "version number does not start with digit". Prefix with ["0~"] (the
   Debian pre-release marker — sorts below any real [0.x.y]) so a
   future numbered release always supersedes the current artefact. *)
let normalize_version v =
  if v = "" then "0"
  else
    let c = v.[0] in
    if c >= '0' && c <= '9' then v else "0~" ^ v

(* Parse a TARGET token into a bare opam package name suitable for use
   in filenames. Strips the [@handle/] overlay prefix and any version
   constraint suffix ([pkg.1.0], [pkg=1.0], [pkg>=1.0]).

   Example: ["@avsm/tangled"] -> ["tangled"], ["utop.2.13"] -> ["utop"]. *)
let clean_pkg_name s =
  let after_slash =
    match String.rindex_opt s '/' with
    | Some i -> String.sub s (i + 1) (String.length s - i - 1)
    | None -> s
  in
  let len = String.length after_slash in
  let is_boundary c = c = '.' || c = '=' || c = '<' || c = '>' in
  let rec scan i =
    if i >= len then after_slash
    else if is_boundary after_slash.[i] then String.sub after_slash 0 i
    else scan (i + 1)
  in
  let n = scan 0 in
  if n = "" then
    Oi.Error.fail_config_error
      "oi dist pkg: cannot derive a package name from TARGET %S" s;
  n

(* Derive the bundle's Spec.t from project mode (cwd's *.opam root) or
   TARGET mode (the first cmdline argument). cmdliner overrides land
   on top. The TARGET-mode version is a placeholder filled in later
   from the solved plan. *)
let derive_spec ~fs ~targets ~pkg_name ~version ~epoch ~maintainer ~homepage
    ~license ~prefix =
  let cwd_s, _ = Workspace.resolved_cwd fs in
  let base : Osdist.Spec.t =
    match targets with
    | [] -> (
        match Osdist.Spec.of_local_project ~cwd:cwd_s with
        | Ok s -> s
        | Error e ->
            Oi.Error.fail_config_error
              "oi dist pkg: cannot derive package from project (%a). Pass \
               TARGET or --pkg-name."
              Osdist.Spec.pp_derive_error e)
    | t :: _ ->
        let name = clean_pkg_name t in
        let v = match version with Some v -> v | None -> "0.0.0" in
        Osdist.Spec.of_target_name ~name ~version:v
  in
  let base =
    match pkg_name with
    | Some _ -> Osdist.Spec.override ?package:pkg_name base
    | None -> base
  in
  let base =
    match version with None -> base | Some v -> { base with version = v }
  in
  Osdist.Spec.override ?epoch ?maintainer ?homepage ?license ?prefix base

(* After [run_makefile] writes [plan.json], peek inside to find the
   node whose [package.name] matches [name]. Prefers a root node over a
   transitive dep when both match. Best-effort: a missing or unparseable
   [plan.json] returns [None]. *)
let resolved_node ~plan_path ~name : D10ir.Plan.node option =
  if not (Sys.file_exists plan_path) then None
  else
    (* IO / decoder errors here mean a missing or malformed [plan.json];
       both are recoverable — the caller falls back to placeholder
       metadata with a warning. *)
    try
      let s = In_channel.with_open_text plan_path In_channel.input_all in
      match D10ir.Plan.of_string s with
      | Error _ -> None
      | Ok plan ->
          let nodes = plan.D10ir.Plan.nodes in
          let by_name (n : D10ir.Plan.node) = n.package.name = name in
          let is_root (n : D10ir.Plan.node) =
            List.mem n.layer_hash plan.D10ir.Plan.roots
          in
          (match List.find_opt (fun n -> is_root n && by_name n) nodes with
          | Some _ as r -> r
          | None -> List.find_opt by_name nodes)
    with Sys_error _ | End_of_file -> None

(* Locate the resolved opam file on disk for a node:
     <reporepo>/v2/<handle>/packages/<pkg>/<pkg>.<version>/opam
   when the node came from an overlay handle.

   For non-overlay (i.e. base reporepo) packages, [overlay = None]; we
   skip — the base reporepo's package layout is the same shape but the
   handle is the literal ["reporepo"] base; we still try it as a fallback. *)
let resolved_opam_path ~reporepo (n : D10ir.Plan.node) =
  let pkg_name = n.package.name in
  let pkg_ver = n.package.version in
  let candidates =
    match n.overlay with
    | Some { handle; _ } ->
        [
          Fmt.str "%s/v2/%s/packages/%s/%s.%s/opam" reporepo handle pkg_name
            pkg_name pkg_ver;
        ]
    | None ->
        [
          Fmt.str "%s/v2/reporepo/packages/%s/%s.%s/opam" reporepo pkg_name
            pkg_name pkg_ver;
        ]
  in
  List.find_opt Sys.file_exists candidates

(* Fold a parsed opam file into [spec], replacing only the fields that
   are still at their [of_target_name] placeholder defaults. Cmdline
   overrides (which were applied earlier in [derive_spec] / via
   [override]) thus win — we only fill in what the user didn't set. *)
let enrich_spec_from_opam (spec : Osdist.Spec.t) ~opam_path =
  match
    Osdist.Spec.of_opam_file ~name:spec.package ~version:spec.version
      ~path:opam_path
  with
  | Error e ->
      Oi.Say.warn "failed to read opam metadata at %s: %s" opam_path e;
      spec
  | Ok o ->
      let placeholder_maint = "Maintainer <maintainer@example.org>" in
      let placeholder_synopsis = Fmt.str "%s — packaged by osdist" spec.package in
      let placeholder_desc =
        Fmt.str "%s, built and packaged by osdist." spec.package
      in
      {
        spec with
        maintainer =
          (if spec.maintainer = placeholder_maint then o.maintainer
           else spec.maintainer);
        homepage = (if spec.homepage = "" then o.homepage else spec.homepage);
        license = (if spec.license = "ISC" then o.license else spec.license);
        synopsis =
          (if spec.synopsis = placeholder_synopsis then o.synopsis
           else spec.synopsis);
        description =
          (if spec.description = placeholder_desc then o.description
           else spec.description);
      }

(* Tar [bundle_dir]'s contents as [<bundle_root>/<pkg>-<ver>.tar.gz] with
   a stable mtime/owner so successive runs of the same content produce
   byte-identical tarballs (good for sha256 reuse downstream). *)
let tarball_of ~sys ~bundle_root ~pkg ~version =
  let dir_name = Fmt.str "%s-%s" pkg version in
  let tarball = bundle_root / Fmt.str "%s.tar.gz" dir_name in
  cmd_run ~sys
    [
      "tar";
      "--sort=name";
      "--mtime=@0";
      "--owner=0";
      "--group=0";
      "--numeric-owner";
      "-czf";
      tarball;
      "-C";
      bundle_root;
      dir_name;
    ];
  tarball

(* [sha256sum FILE] prints [<digest>  FILE\n]. Run it from the tarball's
   directory so the recorded path is just the basename (which is what
   [sha256sum --check] expects), capture stdout via Sysops, and write
   to the sidecar file ourselves — no shell pipeline / redirection. *)
let sha256_sidecar ~sys ~tarball =
  let dir = Filename.dirname tarball in
  let base = Filename.basename tarball in
  let out = tarball ^ ".sha256" in
  let cwd_save = Sys.getcwd () in
  let line =
    Fun.protect
      ~finally:(fun () ->
        try Sys.chdir cwd_save with Sys_error _ -> ())
      (fun () ->
        Sys.chdir dir;
        cmd_out ~sys [ "sha256sum"; base ])
  in
  let payload = if String.length line > 0 then line ^ "\n" else "" in
  Out_channel.with_open_bin out (fun oc ->
      Out_channel.output_string oc payload);
  out

(* Apply packaging-policy version normalisation, emitting an info log
   when the spec's version changes. *)
let normalise_spec_version (spec : Osdist.Spec.t) =
  let normalized = normalize_version spec.version in
  if normalized = spec.version then spec
  else begin
    Oi.Say.info
      "normalised version %s -> %s (packaging policy: must start with digit)"
      spec.version normalized;
    { spec with version = normalized }
  end

(* Lift the resolved version from [node] into [spec], unless the user
   already pinned a version via cmdliner. *)
let with_resolved_version ~user_pinned ~(node : D10ir.Plan.node)
    (spec : Osdist.Spec.t) =
  if user_pinned then spec
  else
    let resolved = normalize_version node.package.version in
    if resolved = spec.version then spec
    else begin
      if resolved = node.package.version then
        Oi.Say.info "resolved %s version: %s" spec.package resolved
      else
        Oi.Say.info "resolved %s version: %s (normalised from %s)" spec.package
          resolved node.package.version;
      { spec with version = resolved }
    end

(* Look up the resolved package's opam file in the reporepo and fold its
   metadata into [spec]. Best-effort: missing opam files just leave the
   placeholder defaults from [of_target_name] in place, with a warning. *)
let with_opam_metadata ~node (spec : Osdist.Spec.t) =
  let reporepo = Oi.Source.Reporepo.env_path () in
  match resolved_opam_path ~reporepo node with
  | None ->
      Oi.Say.warn
        "could not locate resolved opam file for %s (looked under %s); using \
         placeholder metadata"
        spec.package reporepo;
      spec
  | Some opam_path ->
      Oi.Say.info "metadata: %s" opam_path;
      enrich_spec_from_opam spec ~opam_path

(* Stage the makefile flow into a placeholder dir keyed by the package
   name only; once [plan.json] tells us the resolved version we rename
   to the canonical [<pkg>-<ver>/] form. *)
let run_makefile_into_staging ~fs ~harness ~refresh ~registry ~use_registry
    ~with_repos ~with_deps ~toolchain_override ~targets ~staging_dir =
  if Sys.file_exists staging_dir then
    Eio.Path.rmtree ~missing_ok:true Eio.Path.(fs / staging_dir);
  Eio.Path.mkdirs ~exists_ok:true ~perm:0o755 Eio.Path.(fs / staging_dir);
  Dist_runner.run_makefile ~harness ~refresh ~registry ~use_registry
    ~with_repos ~with_deps ~toolchain_override ~targets ~output:staging_dir

let produce ~harness ~refresh ~registry ~use_registry ~with_repos ~with_deps
    ~toolchain_override ~targets ~pkg_name ~version ~epoch ~maintainer
    ~homepage ~license ~prefix ~output =
  let { Harness.fs; sys; _ } = harness in
  let spec =
    derive_spec ~fs ~targets ~pkg_name ~version ~epoch ~maintainer ~homepage
      ~license ~prefix
    |> normalise_spec_version
  in
  Oi.Say.step "solving %s" spec.package;
  let bundle_root = output / "bundle" in
  let staging_dir = bundle_root / spec.package ^ ".staging" in
  run_makefile_into_staging ~fs ~harness ~refresh ~registry ~use_registry
    ~with_repos ~with_deps ~toolchain_override ~targets ~staging_dir;
  let spec =
    match
      resolved_node ~plan_path:(staging_dir / "plan.json") ~name:spec.package
    with
    | None -> spec
    | Some node ->
        spec
        |> with_resolved_version ~user_pinned:(version <> None) ~node
        |> with_opam_metadata ~node
  in
  Oi.Say.step "bundling %s %s" spec.package spec.version;
  let dir_name = Fmt.str "%s-%s" spec.package spec.version in
  let bundle_dir = bundle_root / dir_name in
  if Sys.file_exists bundle_dir then
    Eio.Path.rmtree ~missing_ok:true Eio.Path.(fs / bundle_dir);
  Sys.rename staging_dir bundle_dir;
  write_file ~path:(bundle_dir / "build.sh") bundle_build_sh ~mode:0o755;
  write_file ~path:(bundle_dir / "README.md") (bundle_readme spec) ~mode:0o644;
  let depexts = compute_depexts ~harness ~refresh in
  let spec = { spec with depexts } in
  let tarball =
    tarball_of ~sys ~bundle_root ~pkg:spec.package ~version:spec.version
  in
  let sha = sha256_sidecar ~sys ~tarball in
  let sidecar = Osdist.Spec.sidecar_path ~bundle_path:tarball in
  Osdist.Spec.write_sidecar ~path:sidecar spec;
  Oi.Say.info "  bundle:  %s" tarball;
  Oi.Say.info "  sha256:  %s" sha;
  Oi.Say.info "  sidecar: %s" sidecar;
  (tarball, spec)
