(** Dockerfile generation for [oi docker].

    Emits a standalone static musl build of [oi] on alpine (for CI / manual
    release builds) plus one runnable per-distro image that curls the latest
    [oi] binary from the GitHub releases page and ships the target's depexts.
    Each per-distro image bakes the full
    [oi build --refresh --all --export /registry] followed by
    [s3cmd put --recursive --skip-existing /registry/ s3://oiu/] into its
    build, using BuildKit secrets to supply the S3 credentials. The parallel
    obuilder spec emitter ({!obuilder_spec_one_distro}) drives the same flow
    under [obuilder build --secret …]. *)

module Distro = Dockerfile_opam.Distro

val dockerfile_oi : src_context:string -> Dockerfile.t
(** [dockerfile_oi ~src_context] emits a Dockerfile that builds a static
    musl-linked [oi] binary from the source tree at [src_context] (relative to
    the build context) and exports it as a scratch image at [/oi]. *)

type s3_config = {
  bucket : string;
      (** Target URI for the final [s3cmd put --recursive --skip-existing]
          (e.g. [s3://oiu/]). *)
  host_base : string;  (** [s3cmd] [host_base] endpoint. *)
  host_bucket : string;
      (** [s3cmd] [host_bucket] endpoint (typically the same as [host_base] for
          path-style addressing). *)
  bucket_location : string;
      (** [s3cmd] [bucket_location] hint (e.g. [auto], [us-east-1]). *)
  enable_multipart : bool;
      (** Whether to set [enable_multipart = True] in the generated config. *)
}
(** Static (non-secret) s3cmd configuration baked into the generated
    [/tmp/oi-s3cfg] file at build time. Only the access / secret keys come
    through BuildKit / obuilder secrets at runtime; every field here is visible
    in the spec and image history, so prefer the [oi docker] CLI flags
    ([--s3-bucket], [--s3-host-base], …) over editing the defaults. *)

val default_s3_config : s3_config
(** [default_s3_config] Defaults baked into the emitter when no overrides are
    supplied. Matches the oi maintainers' [~/.s3cfg]: Cloudflare R2 in front of
    [s3://oiu/]. *)

val dockerfile_one_distro :
  ?s3:s3_config -> ?overlay_depexts:string list -> Distro.t -> Dockerfile.t
(** [dockerfile_one_distro] Per-distro build image. Installs the generic build
    toolchain (compilers, headers, [curl], [s3cmd]) together with
    [overlay_depexts] (the union of [depexts:] declared across every reporepo
    handle: solved root closures for handles with [x-root-packages] /
    [x-oi-toolchain-roots], and every package in the overlay's clone for handles
    that declare neither — see {!Build.compute_overlay_depexts_per_distro}). It
    then fetches the latest statically linked [oi-linux-<arch>] and
    [oix-linux-<arch>] from the [oi] GitHub releases page, and a final
    BuildKit-mounted RUN writes [~/.s3cfg] from the supplied secrets, runs
    [oi build --refresh --all --export /registry], and pushes the tree to
    [s3://oiu/]. The secrets ([s3-access-key], [s3-secret-key]) must be supplied
    via [docker build --secret] or compose's [secrets:] block. *)

val obuilder_spec_one_distro :
  ?s3:s3_config -> ?overlay_depexts:string list -> Distro.t -> string
(** [obuilder_spec_one_distro] Per-distro obuilder spec parallel to
    {!dockerfile_one_distro}. Returns the spec body as an s-expression string;
    emit via {!write_file}. Same flow: install depexts + s3cmd, fetch the static
    oi binary, then one [(run …)] that mounts the cache + secrets and drives
    [oi build --export /registry] + [s3cmd put --recursive --skip-existing].
    Secrets are mounted at [/run/secrets/<id>] matching the Dockerfile path.
*)

val one_distro_spec_filename : Distro.t -> string
(** [one_distro_spec_filename] Filename (without directory) for a per-distro
    obuilder spec, e.g. [alpine-3.23.spec]. *)

val dockerfile_project :
  ?overlay_depexts:string list ->
  ?cmd:string ->
  ?generator:string ->
  Distro.t ->
  Dockerfile.t
(** [dockerfile_project] Project-mode Dockerfile: same distro stage as
    {!dockerfile_one_distro}, plus [WORKDIR /src], [COPY . /src], and [RUN cmd]
    (default [oi build]). Used by [oi build --docker] and [oi test --docker].
    [generator] customises the leading "Generated by ..." comment. *)

type opam_vars = {
  os_distribution : string;
  os_family : string;
  os_version : string;
}

val opam_vars_of_distro : Distro.t -> opam_vars
(** [opam_vars_of_distro] Map a supported docker distribution to the opam
    platform variables its opam filters expect. [os-family] follows opam's
    conventions ([debian], [rhel], [alpine], [suse], [arch]), [os-distribution]
    is the per-distro name ([ubuntu], [fedora], etc.), and [os-version] is the
    release string taken from the [Distro.t] tag. [os] is always [linux] for the
    distros this function supports. *)

val one_distro_filename : Distro.t -> string
(** [one_distro_filename] Filename (without directory) for a per-distro
    Dockerfile, e.g. [Dockerfile.alpine-3.23]. *)

val docker_compose_yaml :
  ?s3:s3_config -> distros:Distro.t list -> unit -> string
(** [docker_compose_yaml ~distros ()] emits a compose file whose per-distro
    services drive the registry build entirely at image-build time. Each
    service's [build:] block references the per-distro Dockerfile and lists the
    [s3-access-key] / [s3-secret-key] BuildKit secrets; the top-level [secrets:]
    section reads each from the corresponding host environment variable
    ([S3_ACCESS_KEY] / [S3_SECRET_KEY]). Run with
    [S3_ACCESS_KEY=… S3_SECRET_KEY=… docker compose build]. *)

val write_dockerfile : string -> Dockerfile.t -> unit
(** [write_dockerfile] Serialise a {!Dockerfile.t} to [path] in Dockerfile
    syntax. *)

val write_file : string -> string -> unit
(** [write_file] Write arbitrary string contents to [path]. *)

(** {1 Distro depext primitives}

    Exposed for {!Docker_target} (target-mode Dockerfiles), which renders its
    own template rather than going through {!dockerfile_one_distro} but still
    needs the same base build depexts and install command. *)

val build_depexts : [ `Apk | `Apt | `Yum ] -> string
(** [build_depexts] Space-separated bootstrap toolchain (compiler, [pkg-config],
    [m4], [git], [curl], …) needed before any opam-driven build can run. Library
    [-dev] depexts live in the opam packages' own [depexts:] and flow in via
    [compute_overlay_depexts] — they are NOT listed here. *)

val install_cmd : [ `Apk | `Apt | `Yum ] -> string -> string
(** [install_cmd mgr pkgs] is the full shell command to install [pkgs] under
    package manager [mgr], including any cache cleanup. *)
