name: OxCaml

on: [push, pull_request]

env:
  DUNE_CACHE_ROOT: ${{ github.workspace }}/.cache
  DUNE_CACHE_STORAGE_MODE: hardlink
  DUNE_CACHE: enabled

jobs:
  tests:
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        operating-system: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Restore Oi cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.cache
          key: oi-cache-${{ matrix.operating-system }}
          restore-keys: |
            oi-cache-${{ matrix.operating-system }}-

      - name: Install oi (macOS)
        if: runner.os == 'macOS'
        run: brew install avsm/ocaml/oi

      - name: Install oi (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p "$HOME/.local/bin"
          arch=$(uname -m)
          curl -fsSL -o "$HOME/.local/bin/oi" "https://oi.ci.dev/oi-linux-${arch}"
          chmod +x "$HOME/.local/bin/oi"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          oi config

      - name: Build with oi
        run: |
          oi sync -v
          oi config

      - name: Build with oi
        run: |
          oi exec -- dune build --profile=release

      - name: Do a registry build
        run: |
          oi exec -- oi registry build @avsm


